name: 💡 功能需求
description: 建议一个新功能来改进项目
title: "[功能需求]: "
labels: [功能需求]
body:
- type: markdown
  attributes:
    value: |
      感谢您花时间提出功能需求！您的建议将帮助我们改进项目。
- type: checkboxes
  attributes:
    label: 确认没有重复问题
    description: 请先搜索现有的issues，确保您的功能需求没有被提出过
    options:
    - label: 我已经搜索了现有的issues，确认这不是重复需求
      required: true
- type: textarea
  attributes:
    label: 功能概述
    description: 用一段话描述您希望添加的功能
    placeholder: 请简洁明了地描述您建议的新功能...
  validations:
    required: true
- type: textarea
  attributes:
    label: 为什么需要这个功能？
    description: 请描述这个功能能解决什么问题或满足什么使用场景
    placeholder: |
      例如：
      - 当前遇到的问题或不便
      - 这个功能的使用场景
      - 对用户体验的改进
      - 与其他功能的关联性
  validations:
    required: true